name: Frontend CI/CD

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./flightvisualizer-frontend

      - name: Install Protobuf Compiler (protoc)
        uses: arduino/setup-protoc@v3

      - name: Generate TypeScript from Protobuf
        run: |
          npm install -g ts-proto 
          protoc -I=./api-models --plugin=protoc-gen-ts_proto=./flightvisualizer-frontend/node_modules/.bin/protoc-gen-ts_proto.cmd --ts_proto_out=./flightvisualizer-frontend/src/app/protos --ts_proto_opt=esModuleInterop=true --ts_proto_opt=importSuffix=.js ./api-models/*.proto
        working-directory: .

      - name: Build
        run: npm run build --prod
        working-directory: ./flightvisualizer-frontend

      - name: FTP Upload | Deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: flightvisualizer-frontend/dist/flightvisualizer-frontend/browser/
          protocol: ftp
          timeout: 60000
          security: loose