name: Frontend CI/CD

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./flightvisualizer-frontend

      - name: Build
        run: npm run build --prod
        working-directory: ./flightvisualizer-frontend

      - name: FTP Upload | Deployment
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: flightvisualizer-frontend/dist/flightvisualizer-frontend/browser/
          protocol: ftp
          log-level: verbose
          timeout: 60000
          security: loose
