name: Build and Deploy Backend
on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./flightvisualizer-backend
          file: flightvisualizer-backend/Dockerfile
          tags: erijl/flight-visualizer:latest
          build-args: |
            SPRING_TASK_SCHEDULING_POOL_SIZE=${{ secrets.SPRING_TASK_SCHEDULING_POOL_SIZE }}
            FLIGHT_VISUALIZER_API_URL=${{ secrets.FLIGHT_VISUALIZER_API_URL }}
            FLIGHT_VISUALIZER_API_CLIENT_SECRET=${{ secrets.FLIGHT_VISUALIZER_API_CLIENT_SECRET }}
            FLIGHT_VISUALIZER_API_CLIENT_ID=${{ secrets.FLIGHT_VISUALIZER_API_CLIENT_ID }}
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            FLIGHT_VISUALIZER_CORS_ALLOWED_ORIGINS=${{ secrets.FLIGHT_VISUALIZER_CORS_ALLOWED_ORIGINS }}
            FLIGHT_VISUALIZER_CORS_ALLOWED_METHODS=${{ secrets.FLIGHT_VISUALIZER_CORS_ALLOWED_METHODS }}
            FLIGHT_VISUALIZER_CORS_ALLOWED_HEADERS=${{ secrets.FLIGHT_VISUALIZER_CORS_ALLOWED_HEADERS }}
            FLIGHT_VISUALIZER_CORS_MAXAGE=${{ secrets.FLIGHT_VISUALIZER_CORS_MAXAGE }}
